### ISSUE TITLE
Use "stateful" syntax for elx `cmd.run` states

### ISSUE THREAD

**Issue by lorengordon** [lorengordon/join-domain-formula#21]
The stateful syntax takes better advantage of salt's data and execution models. No need for 'notify' states, as that info would be returned as the 'comment'. It may also allow better integration with a test framework, via the `test_name` parameter.

See:
- https://docs.saltstack.com/en/latest/ref/states/all/salt.states.cmd.html

Example:
- https://github.com/lorengordon/join-domain-formula/blob/master/join-domain/windows/init.sls

**Comment by ferricoxide** [comment]
Umm... *What* notify states. Wasn't aware I'd put any in this set of formula components.

**Comment by lorengordon** [comment]
I didn't actually check, was more preemptive. Using a stateful command/script would also likely negate the need for  any `unless`/`onlyif` parameters, as such checks would be handled by the command/script.

**Comment by ferricoxide** [comment]
While it might negate the need for `requires` statements, whether it negates an `unless`/`onlyif` will depend on what the `unless`/`onlyif` statements are testing for. As used in this formula, the `unless` statements are designed to make the states more idempotent rather than verify the status of a previously-run state within the same formula run-session.

**Comment by lorengordon** [comment]
It would be unlikely to impact the use of `require` parameters. But making the state idempotent is exactly the point of a writing `cmd.run` state with "stateful" syntax. The checks would be incorporated within the command, and the comment would be managed to return useful information about the state of the system and what changes were or were not made.

In some cases, the jinja conditionals wrapping a state can also be incorporated within the command (e.g., test if files exists, branch on result). 

Using the "stateful" syntax makes the sls files much easier to read and treats them like actual states, rather than a simple command execution which in turn requires a bunch of if-else statements and other checks, and the information returned by the state can be much more useful.

**Comment by ferricoxide** [comment]
Mmmkay... So how would *you* rewrite the states to sub in the `stateful` for the `unless` statements?

**Comment by lorengordon** [comment]
The basic piece is just to add an echo as the last line of the command before exiting. Something like this would be a generic structure:

```
    - name: '
      if [ <awesome test> ];
      then;
          echo "changed=no comment=''This is an awesome comment about not needing to make any changes.''";
          exit 0;
      else;
        <whatever command> || exit 1;
        echo "changed=true comment=''I made an awesome change.''";
      fi'
```

It's a little nicer with powershell or python because you can use try/catch blocks, but this should work.

**Comment by ferricoxide** [comment]
Changed the `ssh_allow_group` and `PBIS-installsh` routines to use the `stateful` command-option. However, because they didn't have conditional operations, I left the other `cmd.run` states as is. Should I merge the branch (and close this)?

**Comment by lorengordon** [comment]
Personally, I would use the `stateful` form exclusively, even if there were no condition, to improve reporting in the output and to support better testing in the future. But I'll leave it up to you.

**Comment by ferricoxide** [comment]
Okie doke. I'll add it.

Just for clarity, the desired goal is more than just "- stateful: True" ?
